# Heading
This is text. we can even to LaTeX: $E = mc^2$

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [3]:
b = np.asarray([1, 2, 3])
A = np.eye(3)

In [4]:
A

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [5]:
A.shape

(3, 3)

In [7]:
A[0, 0]

1.0

In [8]:
A[0,1] = 3
A[0,2] = 8
A[1,0] = -2

In [12]:
print(A[0,:])
print(A[0, 0:2])
print(A[0,0:-1])
print(A[:-1,:-1])

[ 1.  3.  8.]
[ 1.  3.]
[ 1.  3.]
[[ 1.  3.]
 [-2.  1.]]


In [15]:
# Elementwise multiplication
A * b

array([[  1.,   6.,  24.],
       [ -2.,   2.,   0.],
       [  0.,   0.,   3.]])

In [14]:
np.dot(A, b)

array([ 31.,   0.,   3.])

In [17]:
# solve linear systems
np.linalg.solve(A,b)

array([-4.14285714, -6.28571429,  3.        ])

In [18]:
# least squares
np.linalg.lstsq(A, b)

(array([-4.14285714, -6.28571429,  3.        ]),
 array([], dtype=float64),
 3,
 array([ 8.65335617,  2.23343758,  0.36219266]))